### ISSUE TITLE
Inject repository interfaces as services

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#978]
- Introduce repository interfaces
- Delcare them as services
- http://php-and-symfony.matthiasnoback.nl/2014/05/inject-a-repository-instead-of-an-entity-manager/

```
            acme_foo_module.generic_base_repository:
                abstract: true
                class: Doctrine\ORM\EntityRepository
                factory: ['@doctrine.orm.default_entity_manager', getRepository]

            acme_foo_module.xyz_repository:
                parent: acme_foo_module.generic_base_repository
                arguments:
                    - AcmeFooModule:MyEntity
```

- Injecting repository interfaces makes dependencies more explicit... if you have for example a `ShopOrderCreator` it requires a `CustomerRepositoryInterface` as well as an `OrderRepositoryInterface`. By calling `$this->orderRepository->persistAndFlush($newOrder)` you do not need to directly use the entity manager.
